# Configuration for nlco_iter.py

[weather]
enabled = true

[weather.location]
lat = 48.2667
lon = 10.9833
city = "Mering"
region = "Bavaria"
country = "Germany"

[smartthings]
# Get your token from https://account.smartthings.com/tokens
# token = "your-token-here"

[social]
post_queue_path = "/home/tom/git/x_twitter_production/saved_posts.json"
posted_posts_path = "/home/tom/git/x_twitter_production/posted_posts.json"
