#!/bin/bash

echo "=== Telegram MCP Setup ==="
echo ""
echo "To use Telegram MCP, you need to:"
echo ""
echo "1. Get your API credentials from https://my.telegram.org"
echo "   - Log in with your phone number"
echo "   - Go to 'API development tools'"
echo "   - Create an app to get API_ID and API_HASH"
echo ""
echo "2. Edit .env.telegram and add your credentials"
echo ""
echo "3. Run the server:"
echo "   export TELEGRAM_API_ID=your_id"
echo "   export TELEGRAM_API_HASH=your_hash"
echo "   python telegram-mcp-repo/main.py"
echo ""
echo "4. For Claude Desktop, add to config:"
echo "   ~/.config/Claude/claude_desktop_config.json (Linux)"
echo "   ~/Library/Application Support/Claude/claude_desktop_config.json (Mac)"
echo ""
echo "Example config:"
cat telegram-mcp-repo/claude_desktop_config.json
echo ""
echo "Current status:"
echo "- telegram-mcp installed: ✓"
echo "- Dependencies installed: ✓"
echo "- Credentials configured: $(if grep -q "your_api_id_here" .env.telegram; then echo "✗ (edit .env.telegram)"; else echo "✓"; fi)"