#!/usr/bin/env python3
"""
Main entry point for abbreviation decoder
Usage: ./abbrev "wdyt"
"""

import sys
import os
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

from abbrev_decoder_dspy import main

if __name__ == "__main__":
    main()